name: Use precompiled binaries and call the CLI testing
on:
  pull_request:
    paths:
      - '**/cli-tests/**'
      - '**/workflows/cli*'
  workflow_dispatch:
    inputs:
      zksolc:
        type: string
        description: "zksolc version, (repo: https://github.com/matter-labs/zksolc-bin/raw/main) e.g. 1.3.23"
        required: true
        default: "1.3.23"
      solc:
        type: string
        description: "solc version, (repo: https://github.com/matter-labs/era-solidity/releases) e.g. 0.8.23"
        required: true
        default: "0.8.24"

env:
  ZKSOLC_VERSION: ${{ github.event.inputs.zksolc || '1.3.23'}}
  SOLC_VERSION: ${{ github.event.inputs.solc || '0.8.24' }}

jobs:
  build_macos_amd64:
    name: MacOS amd64
    runs-on: [ matterlabs-ci-runner ]
    outputs:
      SOLC_VERSION: ${{ env.SOLC_VERSION }}
    steps:
      - name: Binaries Simulation
        run: |
          mkdir -p releases/build_macos_amd64
          wget https://github.com/matter-labs/zksolc-bin/raw/main/macosx-amd64/zksolc-macosx-amd64-v${{ env.ZKSOLC_VERSION }} -O releases/build_macos_amd64/zksolc
      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build_macos_amd64
          path: releases

  build_linux_amd64:
    runs-on: [matterlabs-ci-runner]
    name: Linux amd64
    outputs:
      SOLC_VERSION: ${{ env.SOLC_VERSION }}
    steps:
      - name: Binaries Simulation
        run: |
            mkdir -p releases/build_linux_amd64
            wget https://github.com/matter-labs/zksolc-bin/raw/main/linux-amd64/zksolc-linux-amd64-musl-v${{ env.ZKSOLC_VERSION }} -O releases/build_linux_amd64/zksolc
      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build_linux_amd64
          path: releases

  build_windows_amd64:
    name: Windows amd64 
    runs-on: [matterlabs-ci-runner]
    outputs:
      SOLC_VERSION: ${{ env.SOLC_VERSION }}
    steps:
      - name: Binaries Simulation
        run: |
          mkdir -p releases/build_windows_amd64
          wget https://github.com/matter-labs/zksolc-bin/raw/main/windows-amd64/zksolc-windows-amd64-gnu-v${{ env.ZKSOLC_VERSION }}.exe -O releases/build_windows_amd64/zksolc.exe

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build_windows_amd64
          path: releases


  cli_test_linux_amd64:
    needs:
      - build_linux_amd64
    name: CLI tests on linux
    uses: ./.github/workflows/cli_test_run.yaml
    permissions:
        contents: read
    with:
        name: build_linux_amd64
        path: releases
        runner: matterlabs-ci-runner
        solc_url: https://github.com/matter-labs/era-solidity/releases/download/${{ needs.build_linux_amd64.outputs.SOLC_VERSION }}-1.0.0/solc-linux-amd64-${{ needs.build_linux_amd64.outputs.SOLC_VERSION }}-1.0.0
        

  cli_test_windows:
    needs:
      - build_windows_amd64
    name: CLI tests on Windows
    uses: ./.github/workflows/cli_test_run.yaml
    permissions:
        contents: read
    with:
        name: build_windows_amd64
        path: releases
        runner: windows-2022-github-hosted-16core
        solc_url: https://github.com/matter-labs/era-solidity/releases/download/${{ needs.build_windows_amd64.outputs.SOLC_VERSION }}-1.0.0/solc-windows-amd64-${{ needs.build_windows_amd64.outputs.SOLC_VERSION }}-1.0.0.exe

        
  cli_test_macos_amd64:
    needs:
      - build_macos_amd64
    name: CLI tests on macOS
    uses: ./.github/workflows/cli_test_run.yaml
    permissions:
        contents: read
    with:
        name: build_macos_amd64
        path: releases
        runner: macos-12-large
        solc_url: https://github.com/matter-labs/era-solidity/releases/download/${{ needs.build_macos_amd64.outputs.SOLC_VERSION }}-1.0.0/solc-macosx-amd64-${{ needs.build_macos_amd64.outputs.SOLC_VERSION }}-1.0.0
