name: Unit Tests

# Execute workflow for each PR and with each merge to the trunk
on:
  pull_request:
  push:
    branches:
      - main

# Cancel the workflow if any new changes pushed to a feature branch or the trunk
#
# if the same workspace is shared between runners (today it's true for ARM64 MacOS host)
# /Users/hetzner/actions-runner/_work/era-compiler-solidity
# we cannot allow any concurrent jobs for it, otherwise, CI will fail for 2 PRs tested at the same time
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false # for now, false (put jobs in queue) allowing multiple PR testing consequently (tbd)

env:
  SOLC_VERSION: 0.8.23-1.0.0 # How should we manage solc version updates?
  SOLC_URL: "https://github.com/matter-labs/era-solidity/releases/download"
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  UNIT_TESTS_RESULTS_XML: unit-tests-results.xml
  RUSTC_BOOTSTRAP: 1 # Use rustc in bootstrap mode allowing cargo2junit to use experimental --json feature

jobs:
#  unit-tests-macos:
#    strategy:
#      matrix:
#        include:
#          - name: "MacOS x86"
#            runner: macos-12-large
#            solc-name: "solc-macosx-amd64"
#          - name: "MacOS arm64"
#            runner: [self-hosted, macOS, ARM64]
#            solc-name: "solc-macosx-arm64"
#    runs-on: ${{ matrix.runner }}
#    name: ${{ matrix.name }}
#    defaults:
#      run:
#        shell: zsh {0} # For MacOS hosts, .zprofile is pre-configured
#    steps:
#      # TODO: This step should be done as part of github runners hooks
#      # Users should always expect clean workspace when a new job starts
#      # https://github.blog/changelog/2022-04-04-github-actions-job-management-hooks-for-self-hosted-runners/
#      - name: Cleanup workspace
#        if: ${{ matrix.name }} == "MacOS ARM64"
#        run: |
#          setopt rmstarsilent
#          setopt +o nomatch
#          rm -rf ${{ github.workspace }}/*
#      - name: Checkout source
#        uses: actions/checkout@v4
#      - name: Prepare environment
#        run: |
#          brew install cmake ninja
#      - name: Build LLVM framework
#        run: |
#          cargo install compiler-llvm-builder
#          zkevm-llvm clone
#          zkevm-llvm build
#      - name: Install solc compiler
#        run: |
#          curl --verbose \
#            --location -o "${PWD}/solc" "${SOLC_URL}/${SOLC_VERSION}/${{ matrix.solc-name }}-${SOLC_VERSION}" && \
#            chmod a+x "${PWD}/solc"
#          echo "${PWD}" >> "${GITHUB_PATH}"
#      - name: Build zksolc
#        run: |
#          cargo build --release
#          echo "${PWD}/target/release" >> "${GITHUB_PATH}"
#      - name: Run unit tests
#        continue-on-error: true
#        run: |
#          cargo install cargo2junit
#          cargo test -- -Z unstable-options --format json | cargo2junit > "${UNIT_TESTS_RESULTS_XML}"
#      - name: Upload test results
#        uses: EnricoMi/publish-unit-test-result-action/composite@v2
#        with:
#          check_name: ${{ matrix.name }} Unit Tests Results
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          files: ${{ env.UNIT_TESTS_RESULTS_XML }}
#          action_fail_on_inconclusive: true

  unit-tests-linux:
    strategy:
      matrix:
        include:
#          - name: "Linux x86"
#            runner: matterlabs-ci-runner
#            solc-name: "solc-linux-amd64"
#            target: "x86_64-unknown-linux-musl"
          - name: "Linux arm64"
            runner: matterlabs-ci-runner-arm
            solc-name: "solc-linux-arm64"
            target: "aarch64-unknown-linux-musl"
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.name }}
    container:
      image: matterlabs/llvm_runner_jammy:latest
      credentials:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Prepare environment
        run: |
          rustup target add ${{ matrix.target }}
      - name: Install solc compiler
        run: |
          curl --verbose \
            --location -o "${PWD}/solc" "${SOLC_URL}/${SOLC_VERSION}/${{ matrix.solc-name }}-${SOLC_VERSION}" && \
            chmod a+x "${PWD}/solc"
          echo "${PWD}" >> "${GITHUB_PATH}"
      - name: Build LLVM framework
        run: |
          cargo install compiler-llvm-builder --target ${{ matrix.target }}
          zkevm-llvm clone
          zkevm-llvm build
      - name: Build zksolc
        run: |
          set -x
          if [ "${{ matrix.target }}" = "aarch64-unknown-linux-musl" ]; then
            export RUSTFLAGS="-C link-arg=-Wl,-Bstatic -C link-arg=-lc -C link-arg=-L/usr/lib/llvm-15/lib/clang/15.0.7/lib/linux/ -C link-arg=-lclang_rt.builtins-aarch64"
          fi
          echo "RUSTFLAGS=${RUSTFLAGS}"
          cargo build -vv --release --target ${{ matrix.target }}
          echo "${PWD}/target/${{ matrix.target }}/release" >> "${GITHUB_PATH}"
      - name: Run unit tests
        continue-on-error: true
        run: |
          cargo install cargo2junit
          cargo test --verbose --target ${{ matrix.target }} -- -Z unstable-options --format json | cargo2junit > "${UNIT_TESTS_RESULTS_XML}"
          cat "${UNIT_TESTS_RESULTS_XML}"
      - name: Upload test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_name: ${{ matrix.name }} Unit Tests Results
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ env.UNIT_TESTS_RESULTS_XML }}
          action_fail_on_inconclusive: true

#  unit-tests-windows:
#    name: "Windows"
#    runs-on: windows-2022-github-hosted-16core
#    env:
#      LIBSTDCPP_SOURCE_PATH: "C:/a/_temp/msys64/mingw64/lib/libstdc++.a"
#    defaults:
#      run:
#        shell: msys2 {0}
#    steps:
#      - name: Checkout source
#        uses: actions/checkout@v4
#      - name: Prepare msys2
#        uses: msys2/setup-msys2@v2
#      - name: Prepare env
#        run: |
#          pacman-key --refresh
#          pacman -Sy
#          curl -LO https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-cmake-3.27.7-3-any.pkg.tar.zst
#          pacman --noconfirm -U mingw-w64-x86_64-cmake-3.27.7-3-any.pkg.tar.zst
#          pacman --noconfirm -S --needed --overwrite \
#          base-devel \
#          git \
#          ninja \
#          mingw-w64-x86_64-clang \
#          mingw-w64-x86_64-lld \
#          mingw-w64-x86_64-rust \
#          mingw-w64-x86_64-gcc-libs \
#          mingw-w64-x86_64-gcc
#      - name: Install solc compiler
#        run: |
#          curl --verbose --location -o solc.exe "${SOLC_URL}/${SOLC_VERSION}/solc-windows-amd64-${SOLC_VERSION}.exe"
#      - name: Build LLVM framework
#        run: |
#          cargo install compiler-llvm-builder
#          export PATH="${PATH}:/c/Users/runneradmin/.cargo/bin/"
#          zkevm-llvm clone
#          zkevm-llvm build
#      - name: Build compiler
#        run: |
#          cargo build --release
#      - name: Run unit tests
#        continue-on-error: true
#        run: |
#          cargo install cargo2junit
#          export PATH="$PWD/target/release:$PWD:$PATH:/c/Users/runneradmin/.cargo/bin/"
#          cargo test --verbose -- -Z unstable-options --format json | cargo2junit > "${UNIT_TESTS_RESULTS_XML}"
#          cat "${UNIT_TESTS_RESULTS_XML}"
#      - name: Upload test results
#        uses: EnricoMi/publish-unit-test-result-action/composite@v2
#        with:
#          check_name: Windows Unit Tests Results
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          files: ${{ env.UNIT_TESTS_RESULTS_XML }}
#          action_fail_on_inconclusive: true
